name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make sub-tests
      run: cd build && make sub-tests
    - name: run tests
      run: cd tests && ./tests
